### ISSUE TITLE
Psych::DisallowedClass Exception: Tried to load unspecified class: Symbol

### ISSUE THREAD

**Issue by liukun-lk** [jasl-lab/options_model#1]
Ruby version: `ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-darwin18`
options_model: 0.0.15

```ruby
# ~/.rvm/gems/ruby-2.6.1/gems/options_model-0.0.15/lib/options_model/concerns/serialization.rb

# yaml = "---\n:account:\n  :search_member: true\n  :member: true\n"
hash = YAML.safe_load(yaml, permitted_classes: permitted_attribute_classes) || {}
```
will raise `Psych::DisallowedClass (Tried to load unspecified class: Symbol)` and if I use `YAML.load` like 0.0.12. There is no more throwing exception.

**Comment by jasl** [comment]
Wait a seconds and try the latest version (0.0.16)

The problem is `Symbol` is not in `YAML.safe_load` whitelist by default, I expose `permitted_attribute_classes` that allow you control this manually.

You need to do like this

```ruby
class Config < OptionsModel::Base
  # Define attributes

  def permitted_attribute_classes
    PERMITTED_ATTRIBUTE_CLASSES
  end
end
```

But I think I'm overthinking, `Symbol` in `YAML` is common case, so I add `Symbol` to the default whitelist.

**Comment by jasl** [comment]
@liukun-lk if 0.0.16 works, let me know

**Comment by liukun-lk** [comment]
@jasl It works. Thanks
